version: "2" # version of docker compose

services:
  chatbox:
    build: .
    image: chatbox-image:latest
    container_name: chatbox-container
    hostname: chatbox
    restart: "no"
    environment:
      - APP_PORT=5000
    ports:
      - "5000:5000"
